### PR TITLE
IDFA Quick Fix: This is a very quick and dirty patch that should allow the upload of app...

### PR DESCRIPTION
**Pull request by stephenfeather**
...s to the app store.

I simply removed/commented the usage of the AdSupport framework.  This builds apps against 3.2.2.GA.
Version bumped to 3.1.2.
This WILL break the fb install tracking.
THIS NEEDS TO BE TESTED.

### CODE REVIEW

**Comment by pastuxso** [comment]
Currently i'm testing your branch.

**Comment by jenslukas** [comment]
Any news on that one? This is preventing me from pushing my app to the store :(
If I could help just let me know

**Comment by mzaharenkov** [comment]
Download version 3.1.2 https://github.com/sfeather/ti.facebook/tree/IDFA/ios
It helped me

**Comment by pastuxso** [comment]
It works for me, the application was posted at the apple store.

**Comment by ingo** [comment]
Hi All--please note that Facebook closed the bug on their side for this issue: https://developers.facebook.com/bugs/242477629268301. It appears that there may not be an updated SDK--you just need to be careful in how you submit your application.

**Pull request closed without merging**
