### PR TITLE
Add iOS url scheme suffix feature

### PR DESCRIPTION
**Pull request by arnaudbesnier**
This is a feature we use a lot to have severals iOS apps using the same Facebook App.

You can find the Facebook documentation here : https://developers.facebook.com/docs/howtos/share-appid-across-multiple-apps-ios-sdk/

I posted a Q&A on this topic : http://developer.appcelerator.com/question/137857/how-to-define-a-specific-facebook-url-scheme-suffix-for-my-ios-app
I also posted a JIRA : https://jira.appcelerator.org/browse/TIMOB-9701

This JIRA is almost 1 year-old and still opened, we patched your module to make it works on our apps. It would be great to integrate this patch to the main code.

### CODE REVIEW

**Comment by joshualambert** [comment]
I agree-- this should be merged in. +1

**Comment by jhaynie** [comment]
thanks for the pull request.

**Comment by jayniz** [comment]
I need this as well +1

**Comment by etruta** [comment]
:+1:

**Pull request closed without merging**
